// <auto-generated />
using System;
using LiveWPF_Week6.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseApp.Migrations
{
    [DbContext(typeof(ShoppingCardContext))]
    [Migration("20201006100810_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LiveWPF_Week6.Models.ItemCatogory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("ItemCatogories");
                });

            modelBuilder.Entity("LiveWPF_Week6.Models.ShoppingItem", b =>
                {
                    b.Property<int>("ArtNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ItemCatogoryId")
                        .HasColumnType("int");

                    b.Property<string>("Manufactuer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.HasKey("ArtNumber");

                    b.HasIndex("ItemCatogoryId");

                    b.ToTable("ShoppingItem");
                });

            modelBuilder.Entity("LiveWPF_Week6.Models.ShoppingItem", b =>
                {
                    b.HasOne("LiveWPF_Week6.Models.ItemCatogory", "ItemCatogory")
                        .WithMany()
                        .HasForeignKey("ItemCatogoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
